build:
  image: python:3.9-alpine  # nosetests uses collections.Mapping which is discontinued in 3.10
  services:
    - docker:dind
  script:
    - apk add docker-cli
    - pip install -r requirements.txt awscli
    - nosetests --with-xunit -v tests/
    - cd src/ && python ./setup.py sdist && cd ..
    - docker build . -t 855023211239.dkr.ecr.eu-west-1.amazonaws.com/queue-alerter:$CI_PIPELINE_IID
    - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 855023211239.dkr.ecr.eu-west-1.amazonaws.com
    - docker push 855023211239.dkr.ecr.eu-west-1.amazonaws.com/queue-alerter:$CI_PIPELINE_IID
  artifacts:
    paths:
      - src/dist/queue-alerter-1.0.tar.gz
    reports:
      junit:
      - nosetests.xml

