build:
  image: python:3.10-alpine
  services:
    - docker:dind
  script:
    - apk add docker-cli aws-cli
    - pip install -r requirements.txt
    - nosetests --with-xunit -v tests/
    - cd src/ && python ./setup.py sdist
    - docker build . -t 855023211239.dkr.ecr.eu-west-1.amazonaws.com/queue-alerter:$CI_PIPELINE_IID
    - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 855023211239.dkr.ecr.eu-west-1.amazonaws.com
    - docker push 855023211239.dkr.ecr.eu-west-1.amazonaws.com/queue-alerter:$CI_PIPELINE_IID
  artifacts:
    paths:
      - src/dist/queue-alerter-1.0.tar.gz
    reports:
      junit:
      - nosetests.xml

