build:
  image: python:3.9-alpine  # nosetests uses collections.Mapping which is discontinued in 3.10
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs" #this is mounted by the gitlab CI system so is populated from the dind service
    DOCKER_HOST: tcp://docker:2376
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_VERIFY: 1
  script:
    - apk add docker-cli aws-cli
    - pip install -r requirements.txt
    - nosetests --with-xunit -v tests/
    - cd src/ && python ./setup.py sdist && cd ..
    - mkdir ~/.docker && cp -a /certs/client/*.pem ~/.docker
    - docker build . -t 855023211239.dkr.ecr.eu-west-1.amazonaws.com/queue-alerter:$CI_PIPELINE_IID
    - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 855023211239.dkr.ecr.eu-west-1.amazonaws.com
    - docker push 855023211239.dkr.ecr.eu-west-1.amazonaws.com/queue-alerter:$CI_PIPELINE_IID
  artifacts:
    paths:
      - src/dist/queue-alerter-1.0.tar.gz
    reports:
      junit:
      - nosetests.xml

